/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface AlchemistAcademyInterface extends ethers.utils.Interface {
  functions: {
    "DAOAddress()": FunctionFragment;
    "MINTER_ROLE()": FunctionFragment;
    "alchemistCounter()": FunctionFragment;
    "alchemistImpl()": FunctionFragment;
    "chymeList(address)": FunctionFragment;
    "createNewChyme(uint8,uint8,uint8,address,address,uint256)": FunctionFragment;
    "elixirImpl()": FunctionFragment;
    "getChymeInfo(address)": FunctionFragment;
    "initialize(address,address,address,address,address,address)": FunctionFragment;
    "priceFromOracle(address)": FunctionFragment;
    "setDAORewardContract(address)": FunctionFragment;
    "steadyDAOReward()": FunctionFragment;
    "steadyDAOToken()": FunctionFragment;
    "steadyImpl()": FunctionFragment;
    "treasury()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DAOAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MINTER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "alchemistCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "alchemistImpl",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "chymeList", values: [string]): string;
  encodeFunctionData(
    functionFragment: "createNewChyme",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "elixirImpl",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getChymeInfo",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "priceFromOracle",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setDAORewardContract",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "steadyDAOReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "steadyDAOToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "steadyImpl",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;

  decodeFunctionResult(functionFragment: "DAOAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MINTER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "alchemistCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "alchemistImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "chymeList", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createNewChyme",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "elixirImpl", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getChymeInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceFromOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDAORewardContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "steadyDAOReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "steadyDAOToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "steadyImpl", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;

  events: {
    "AlchemistForged(address,address,uint8,address)": EventFragment;
    "Chymed(address,uint256,uint256,string)": EventFragment;
    "Initialized(uint8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AlchemistForged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Chymed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
}

export type AlchemistForgedEvent = TypedEvent<
  [string, string, number, string] & {
    alchemist: string;
    priceOracle: string;
    fees: number;
    steadyImplForChyme: string;
  }
>;

export type ChymedEvent = TypedEvent<
  [string, BigNumber, BigNumber, string] & {
    chyme: string;
    fees: BigNumber;
    approvalStatus: BigNumber;
    symbol: string;
  }
>;

export type InitializedEvent = TypedEvent<[number] & { version: number }>;

export class AlchemistAcademy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: AlchemistAcademyInterface;

  functions: {
    DAOAddress(overrides?: CallOverrides): Promise<[string]>;

    MINTER_ROLE(overrides?: CallOverrides): Promise<[string]>;

    alchemistCounter(overrides?: CallOverrides): Promise<[BigNumber]>;

    alchemistImpl(overrides?: CallOverrides): Promise<[string]>;

    chymeList(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [number, number, number, string, string, string, BigNumber] & {
        decimals: number;
        fees: number;
        DAOApproved: number;
        oracleAddress: string;
        steadyImplForChyme: string;
        symbol: string;
        timeToMaturity: BigNumber;
      }
    >;

    createNewChyme(
      _decimals: BigNumberish,
      _fees: BigNumberish,
      _approvalStatus: BigNumberish,
      _chyme: string,
      _oracleAddress: string,
      _timeToMaturity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    elixirImpl(overrides?: CallOverrides): Promise<[string]>;

    getChymeInfo(
      _chyme: string,
      overrides?: CallOverrides
    ): Promise<
      [string, number, number, BigNumber, string, string] & {
        oracleAddress: string;
        fees: number;
        decimals: number;
        timeToMaturity: BigNumber;
        symbol: string;
        steadyImplForChyme: string;
      }
    >;

    initialize(
      _elixirImpl: string,
      _steadyImpl: string,
      _treasury: string,
      _alchemistImpl: string,
      _DAOAddress: string,
      _steadyDAOReward: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    priceFromOracle(
      _priceOracle: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { price: BigNumber }>;

    setDAORewardContract(
      _steadyDAOReward: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    steadyDAOReward(overrides?: CallOverrides): Promise<[string]>;

    steadyDAOToken(overrides?: CallOverrides): Promise<[string]>;

    steadyImpl(overrides?: CallOverrides): Promise<[string]>;

    treasury(overrides?: CallOverrides): Promise<[string]>;
  };

  DAOAddress(overrides?: CallOverrides): Promise<string>;

  MINTER_ROLE(overrides?: CallOverrides): Promise<string>;

  alchemistCounter(overrides?: CallOverrides): Promise<BigNumber>;

  alchemistImpl(overrides?: CallOverrides): Promise<string>;

  chymeList(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [number, number, number, string, string, string, BigNumber] & {
      decimals: number;
      fees: number;
      DAOApproved: number;
      oracleAddress: string;
      steadyImplForChyme: string;
      symbol: string;
      timeToMaturity: BigNumber;
    }
  >;

  createNewChyme(
    _decimals: BigNumberish,
    _fees: BigNumberish,
    _approvalStatus: BigNumberish,
    _chyme: string,
    _oracleAddress: string,
    _timeToMaturity: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  elixirImpl(overrides?: CallOverrides): Promise<string>;

  getChymeInfo(
    _chyme: string,
    overrides?: CallOverrides
  ): Promise<
    [string, number, number, BigNumber, string, string] & {
      oracleAddress: string;
      fees: number;
      decimals: number;
      timeToMaturity: BigNumber;
      symbol: string;
      steadyImplForChyme: string;
    }
  >;

  initialize(
    _elixirImpl: string,
    _steadyImpl: string,
    _treasury: string,
    _alchemistImpl: string,
    _DAOAddress: string,
    _steadyDAOReward: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  priceFromOracle(
    _priceOracle: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setDAORewardContract(
    _steadyDAOReward: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  steadyDAOReward(overrides?: CallOverrides): Promise<string>;

  steadyDAOToken(overrides?: CallOverrides): Promise<string>;

  steadyImpl(overrides?: CallOverrides): Promise<string>;

  treasury(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    DAOAddress(overrides?: CallOverrides): Promise<string>;

    MINTER_ROLE(overrides?: CallOverrides): Promise<string>;

    alchemistCounter(overrides?: CallOverrides): Promise<BigNumber>;

    alchemistImpl(overrides?: CallOverrides): Promise<string>;

    chymeList(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [number, number, number, string, string, string, BigNumber] & {
        decimals: number;
        fees: number;
        DAOApproved: number;
        oracleAddress: string;
        steadyImplForChyme: string;
        symbol: string;
        timeToMaturity: BigNumber;
      }
    >;

    createNewChyme(
      _decimals: BigNumberish,
      _fees: BigNumberish,
      _approvalStatus: BigNumberish,
      _chyme: string,
      _oracleAddress: string,
      _timeToMaturity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    elixirImpl(overrides?: CallOverrides): Promise<string>;

    getChymeInfo(
      _chyme: string,
      overrides?: CallOverrides
    ): Promise<
      [string, number, number, BigNumber, string, string] & {
        oracleAddress: string;
        fees: number;
        decimals: number;
        timeToMaturity: BigNumber;
        symbol: string;
        steadyImplForChyme: string;
      }
    >;

    initialize(
      _elixirImpl: string,
      _steadyImpl: string,
      _treasury: string,
      _alchemistImpl: string,
      _DAOAddress: string,
      _steadyDAOReward: string,
      overrides?: CallOverrides
    ): Promise<void>;

    priceFromOracle(
      _priceOracle: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setDAORewardContract(
      _steadyDAOReward: string,
      overrides?: CallOverrides
    ): Promise<void>;

    steadyDAOReward(overrides?: CallOverrides): Promise<string>;

    steadyDAOToken(overrides?: CallOverrides): Promise<string>;

    steadyImpl(overrides?: CallOverrides): Promise<string>;

    treasury(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "AlchemistForged(address,address,uint8,address)"(
      alchemist?: string | null,
      priceOracle?: null,
      fees?: null,
      steadyImplForChyme?: null
    ): TypedEventFilter<
      [string, string, number, string],
      {
        alchemist: string;
        priceOracle: string;
        fees: number;
        steadyImplForChyme: string;
      }
    >;

    AlchemistForged(
      alchemist?: string | null,
      priceOracle?: null,
      fees?: null,
      steadyImplForChyme?: null
    ): TypedEventFilter<
      [string, string, number, string],
      {
        alchemist: string;
        priceOracle: string;
        fees: number;
        steadyImplForChyme: string;
      }
    >;

    "Chymed(address,uint256,uint256,string)"(
      chyme?: null,
      fees?: null,
      approvalStatus?: null,
      symbol?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, string],
      {
        chyme: string;
        fees: BigNumber;
        approvalStatus: BigNumber;
        symbol: string;
      }
    >;

    Chymed(
      chyme?: null,
      fees?: null,
      approvalStatus?: null,
      symbol?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, string],
      {
        chyme: string;
        fees: BigNumber;
        approvalStatus: BigNumber;
        symbol: string;
      }
    >;

    "Initialized(uint8)"(
      version?: null
    ): TypedEventFilter<[number], { version: number }>;

    Initialized(
      version?: null
    ): TypedEventFilter<[number], { version: number }>;
  };

  estimateGas: {
    DAOAddress(overrides?: CallOverrides): Promise<BigNumber>;

    MINTER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    alchemistCounter(overrides?: CallOverrides): Promise<BigNumber>;

    alchemistImpl(overrides?: CallOverrides): Promise<BigNumber>;

    chymeList(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    createNewChyme(
      _decimals: BigNumberish,
      _fees: BigNumberish,
      _approvalStatus: BigNumberish,
      _chyme: string,
      _oracleAddress: string,
      _timeToMaturity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    elixirImpl(overrides?: CallOverrides): Promise<BigNumber>;

    getChymeInfo(_chyme: string, overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _elixirImpl: string,
      _steadyImpl: string,
      _treasury: string,
      _alchemistImpl: string,
      _DAOAddress: string,
      _steadyDAOReward: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    priceFromOracle(
      _priceOracle: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setDAORewardContract(
      _steadyDAOReward: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    steadyDAOReward(overrides?: CallOverrides): Promise<BigNumber>;

    steadyDAOToken(overrides?: CallOverrides): Promise<BigNumber>;

    steadyImpl(overrides?: CallOverrides): Promise<BigNumber>;

    treasury(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    DAOAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MINTER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    alchemistCounter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    alchemistImpl(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    chymeList(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createNewChyme(
      _decimals: BigNumberish,
      _fees: BigNumberish,
      _approvalStatus: BigNumberish,
      _chyme: string,
      _oracleAddress: string,
      _timeToMaturity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    elixirImpl(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getChymeInfo(
      _chyme: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _elixirImpl: string,
      _steadyImpl: string,
      _treasury: string,
      _alchemistImpl: string,
      _DAOAddress: string,
      _steadyDAOReward: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    priceFromOracle(
      _priceOracle: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setDAORewardContract(
      _steadyDAOReward: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    steadyDAOReward(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    steadyDAOToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    steadyImpl(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    treasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
