/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ISteadyDAORewards,
  ISteadyDAORewardsInterface,
} from "../ISteadyDAORewards";

const _abi = [
  {
    inputs: [
      {
        internalType: "enum ISteadyDAORewards.actionType",
        name: "action",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "steadyAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "fees",
        type: "uint256",
      },
    ],
    name: "performAction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISteadyDAORewards__factory {
  static readonly abi = _abi;
  static createInterface(): ISteadyDAORewardsInterface {
    return new utils.Interface(_abi) as ISteadyDAORewardsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISteadyDAORewards {
    return new Contract(address, _abi, signerOrProvider) as ISteadyDAORewards;
  }
}
