/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ITreasure, ITreasureInterface } from "../ITreasure";

const _abi = [
  {
    inputs: [],
    name: "generateHeader",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "timeLeft",
        type: "string",
      },
      {
        internalType: "string",
        name: "to",
        type: "string",
      },
    ],
    name: "generateTreasureChest",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

export class ITreasure__factory {
  static readonly abi = _abi;
  static createInterface(): ITreasureInterface {
    return new utils.Interface(_abi) as ITreasureInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITreasure {
    return new Contract(address, _abi, signerOrProvider) as ITreasure;
  }
}
