/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  SteadyDAOReward,
  SteadyDAORewardInterface,
} from "../SteadyDAOReward";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "enum ISteadyDAORewards.actionType",
        name: "",
        type: "uint8",
      },
    ],
    name: "PerformedAction",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "enum ISteadyDAORewards.actionType",
        name: "action",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "performAction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610203806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80634478270e14610030575b600080fd5b61004a600480360381019061004591906100e8565b61004c565b005b7fe1da30583a1bdae223cff418e205e0a5e4e8bba012a8c76e5fe36731eb3f280b8360405161007b91906101b2565b60405180910390a1505050565b600080fd5b6005811061009a57600080fd5b50565b6000813590506100ac8161008d565b92915050565b6000819050919050565b6100c5816100b2565b81146100d057600080fd5b50565b6000813590506100e2816100bc565b92915050565b60008060006060848603121561010157610100610088565b5b600061010f8682870161009d565b9350506020610120868287016100d3565b9250506040610131868287016100d3565b9150509250925092565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052602160045260246000fd5b6005811061017b5761017a61013b565b5b50565b600081905061018c8261016a565b919050565b600061019c8261017e565b9050919050565b6101ac81610191565b82525050565b60006020820190506101c760008301846101a3565b9291505056fea264697066735822122064d01b1210dc78d5605a740fac5ae3b70849745f39f3f6638ff140db532217e964736f6c634300080b0033";

export class SteadyDAOReward__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<SteadyDAOReward> {
    return super.deploy(overrides || {}) as Promise<SteadyDAOReward>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): SteadyDAOReward {
    return super.attach(address) as SteadyDAOReward;
  }
  connect(signer: Signer): SteadyDAOReward__factory {
    return super.connect(signer) as SteadyDAOReward__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SteadyDAORewardInterface {
    return new utils.Interface(_abi) as SteadyDAORewardInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SteadyDAOReward {
    return new Contract(address, _abi, signerOrProvider) as SteadyDAOReward;
  }
}
