/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  SteadyDAOReward,
  SteadyDAORewardInterface,
} from "../SteadyDAOReward";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "enum ISteadyDAORewards.actionType",
        name: "",
        type: "uint8",
      },
    ],
    name: "PerformedAction",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "enum ISteadyDAORewards.actionType",
        name: "action",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "performAction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610160806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063a9d7fad514610030575b600080fd5b61004361003e366004610082565b610045565b005b7fe1da30583a1bdae223cff418e205e0a5e4e8bba012a8c76e5fe36731eb3f280b8460405161007491906100e9565b60405180910390a150505050565b6000806000806080858703121561009857600080fd5b8435600581106100a757600080fd5b93506020850135925060408501359150606085013573ffffffffffffffffffffffffffffffffffffffff811681146100de57600080fd5b939692955090935050565b6020810160058310610124577f4e487b7100000000000000000000000000000000000000000000000000000000600052602160045260246000fd5b9190529056fea26469706673582212200b7fd8adce54769ab5fa97d0de6a72ed7460b890e8d2160ff127fc20f9a1468864736f6c63430008100033";

export class SteadyDAOReward__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<SteadyDAOReward> {
    return super.deploy(overrides || {}) as Promise<SteadyDAOReward>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): SteadyDAOReward {
    return super.attach(address) as SteadyDAOReward;
  }
  connect(signer: Signer): SteadyDAOReward__factory {
    return super.connect(signer) as SteadyDAOReward__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SteadyDAORewardInterface {
    return new utils.Interface(_abi) as SteadyDAORewardInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SteadyDAOReward {
    return new Contract(address, _abi, signerOrProvider) as SteadyDAOReward;
  }
}
